
services:
  - type: web
    name: mcp-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.server:starlette_app --host 0.0.0.0 --port 10000
